name: ClaudeTokenBar
options:
  bundleIdPrefix: com.bernardogontijo
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"

targets:
  ClaudeTokenBar:
    type: application
    platform: macOS
    sources:
      - ClaudeTokenBar
    info:
      path: ClaudeTokenBar/Info.plist
      properties:
        LSUIElement: true
        CFBundleDisplayName: ClaudeTokenBar
        CFBundleName: ClaudeTokenBar
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
    entitlements:
      path: ClaudeTokenBar/ClaudeTokenBar.entitlements
    settings:
      base:
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        PRODUCT_BUNDLE_IDENTIFIER: com.bernardogontijo.ClaudeTokenBar
        INFOPLIST_FILE: ClaudeTokenBar/Info.plist
        ENABLE_HARDENED_RUNTIME: false
